In [1]:
import numpy as np

#### Advanced array creation with specific dtypes

In [2]:
complex_array = np.array([1+2j, 3+4j], dtype=np.complex128)
print("Complex array:", complex_array)

Complex array: [1.+2.j 3.+4.j]


#### Memory layout optimization (order parameter)

In [3]:
c_order_array = np.array([[1, 2, 3], [4, 5, 6]], order='C')
f_order_array = np.array([[1, 2, 3], [4, 5, 6]], order='F')
print("C-order array:", c_order_array)
print("F-order array:", f_order_array)

C-order array: [[1 2 3]
 [4 5 6]]
F-order array: [[1 2 3]
 [4 5 6]]


#### Memory views and broadcasting

In [4]:
x = np.arange(6).reshape(2, 3)
y = x[:, np.newaxis, :]
print("Memory view and broadcasting array:\n", y)

Memory view and broadcasting array:
 [[[0 1 2]]

 [[3 4 5]]]


#### Manipulating the shape and size of arrays

In [5]:
flattened = x.flatten()
print("Flattened array:", flattened)

Flattened array: [0 1 2 3 4 5]


In [6]:
raveled = x.ravel()
print("Raveled array:", raveled)

Raveled array: [0 1 2 3 4 5]


#### Tile and repeat arrays

In [7]:
tiled = np.tile(x, (2, 1))
print("Tiled array:\n", tiled)

Tiled array:
 [[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]


In [8]:
repeated = np.repeat(x, 2, axis=0)
print("Repeated array:\n", repeated)

Repeated array:
 [[0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]]


#### Masked arrays

In [9]:
masked_array = np.ma.array(x, mask=x > 2)
print("Masked array:\n", masked_array)

Masked array:
 [[0 1 2]
 [-- -- --]]


### Advanced linear algebra operations

#### Singular Value Decomposition (SVD)

In [10]:
u, s, vh = np.linalg.svd(x, full_matrices=False)
print("U matrix:\n", u)
print("Singular values:", s)
print("V^H matrix:\n", vh)

U matrix:
 [[-0.27472113 -0.96152395]
 [-0.96152395  0.27472113]]
Singular values: [7.34846923 1.        ]
V^H matrix:
 [[-0.39254051 -0.56077215 -0.7290038 ]
 [ 0.82416338  0.13736056 -0.54944226]]


#### QR Decomposition

In [11]:
q, r = np.linalg.qr(x)
print("Q matrix:\n", q)
print("R matrix:\n", r)

Q matrix:
 [[ 0. -1.]
 [-1.  0.]]
R matrix:
 [[-3. -4. -5.]
 [ 0. -1. -2.]]


#### Cholesky Decomposition

In [12]:
A = np.array([[1, 2], [2, 5]])
cholesky_decomp = np.linalg.cholesky(A)
print("Cholesky decomposition:\n", cholesky_decomp)

Cholesky decomposition:
 [[1. 0.]
 [2. 1.]]


#### Eigenvalue decomposition

In [13]:
eigenvalues, eigenvectors = np.linalg.eigh(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [0.17157288 5.82842712]
Eigenvectors:
 [[-0.92387953  0.38268343]
 [ 0.38268343  0.92387953]]


#### Fourier Transforms

In [15]:
fft_array = np.fft.fft([1, 2, 3, 4])
print("FFT of array:", fft_array)

FFT of array: [10.+0.j -2.+2.j -2.+0.j -2.-2.j]


In [16]:
ifft_array = np.fft.ifft(fft_array)
print("Inverse FFT of array:", ifft_array)

Inverse FFT of array: [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


#### Gradient and numerical differentiation

In [18]:
x = np.linspace(0, 10, 15)
y = np.sin(x)
gradient = np.gradient(y, x)
print("Gradient of y with respect to x:", gradient)

Gradient of y with respect to x: [ 0.91710906  0.69293215  0.12999645 -0.49649157 -0.88025613 -0.83368344
 -0.37954184  0.26014916  0.77265913  0.90743359  0.59858436 -0.00289918
 -0.60296538 -0.90825549 -0.9556918 ]


### Advanced statistical functions

In [19]:
percentile_90 = np.percentile(x, 90)
print("90th percentile:", percentile_90)

quantiles = np.quantile(x, [0.25, 0.5, 0.75])
print("Quantiles (25%, 50%, 75%):", quantiles)

90th percentile: 9.0
Quantiles (25%, 50%, 75%): [2.5 5.  7.5]


### Advanced random number generation

#### Random samples from a multivariate normal distribution

In [20]:
mean = [0, 0]
cov = [[1, 0.5], [0.5, 1]]
multivar_normal = np.random.multivariate_normal(mean, cov, 1000)
print("Multivariate normal samples:\n", multivar_normal[:5])

Multivariate normal samples:
 [[ 0.93606914  1.15691852]
 [-1.28852235 -0.13595945]
 [ 0.25266096  0.2836092 ]
 [-0.82698785 -1.04721833]
 [ 0.62612241 -0.72883211]]


### Working with large datasets

#### Memory-mapped files for large datasets

In [22]:
large_array = np.memmap('large_array.dat', dtype='float32', mode='w+', shape=(1000, 1000))
large_array[:] = np.random.random((1000, 1000))
print("Large array using memmap:\n", large_array)

Large array using memmap:
 [[0.22171208 0.73977745 0.19573109 ... 0.06419918 0.3911122  0.71369445]
 [0.4550585  0.7412077  0.5594306  ... 0.9787705  0.49550235 0.57995635]
 [0.31516382 0.31833953 0.2724072  ... 0.73119575 0.6358822  0.45537663]
 ...
 [0.04684654 0.19707555 0.30127618 ... 0.77955985 0.00743755 0.39149788]
 [0.8189556  0.1627267  0.5308674  ... 0.39167887 0.7441131  0.9988899 ]
 [0.32805124 0.67676634 0.53329086 ... 0.35035086 0.09388423 0.38440704]]


### Sliding window view for advanced slicing

In [23]:
from numpy.lib.stride_tricks import sliding_window_view
array = np.arange(10)
window_size = 3
sliding_windows = sliding_window_view(array, window_shape=window_size)
print("Sliding window view:\n", sliding_windows)

Sliding window view:
 [[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


### Sparse matrix operations with Scipy integration

In [26]:
from scipy import sparse
a = np.arange(25).reshape(5, 5)
sparse_matrix = sparse.csr_matrix(a)
print("Sparse matrix:\n", sparse_matrix)

Sparse matrix:
   (0, 1)	1
  (0, 2)	2
  (0, 3)	3
  (0, 4)	4
  (1, 0)	5
  (1, 1)	6
  (1, 2)	7
  (1, 3)	8
  (1, 4)	9
  (2, 0)	10
  (2, 1)	11
  (2, 2)	12
  (2, 3)	13
  (2, 4)	14
  (3, 0)	15
  (3, 1)	16
  (3, 2)	17
  (3, 3)	18
  (3, 4)	19
  (4, 0)	20
  (4, 1)	21
  (4, 2)	22
  (4, 3)	23
  (4, 4)	24


### Sparse matrix operations

In [28]:
sparse_matrix_sum = sparse_matrix.sum()
print("Sum of sparse matrix elements:", sparse_matrix_sum)

Sum of sparse matrix elements: 300


In [29]:
# element wise
squared_elements = np.square(a)
print("Squared elements using np.ufunc:\n", squared_elements)

Squared elements using np.ufunc:
 [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


### Broadcasting with np.newaxis for higher-dimensional operations

In [30]:
array_3d = array[:, np.newaxis]
print("Array expanded to 3D with newaxis:\n", array_3d)

Array expanded to 3D with newaxis:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


### Vectorized string operations

In [31]:
string_array = np.array(['hello', 'world', 'numpy'])
uppercased = np.char.upper(string_array)
print("Uppercased string array:", uppercased)

Uppercased string array: ['HELLO' 'WORLD' 'NUMPY']


### Vectorized datetime operations

In [32]:
dates = np.array(['2023-01-01', '2024-01-01'], dtype='datetime64')
date_diffs = dates - np.datetime64('2023-01-01')
print("Date differences in days:", date_diffs)

Date differences in days: [  0 365]
