In [1]:
# import library
import numpy as np

#### Creating arrays with random values from a normal distribution

In [2]:
# mean=0, std=1
normal_dist = np.random.normal(loc=0, scale=1, size=(3, 3)) 
print("Normal distribution array:\n", normal_dist)

Normal distribution array:
 [[-1.17078181  1.81744142 -1.23838881]
 [-0.89486856 -0.70308041 -0.97903639]
 [-0.00214532 -0.13319196 -1.01465773]]


#### Generating random integers

In [4]:
# low, high, size
rand_ints = np.random.randint(0, 10, size=(3, 3))  
print("Random integers array:\n", rand_ints)

Random integers array:
 [[7 2 5]
 [1 5 9]
 [7 3 2]]


#### Creating an array with random values from a uniform distribution

In [5]:
# low, high, size
uniform_dist = np.random.uniform(low=0, high=1, size=(3, 3)) 
print("Uniform distribution array:\n", uniform_dist)

Uniform distribution array:
 [[0.85537442 0.03627551 0.19870344]
 [0.13044849 0.46198622 0.01876896]
 [0.23510354 0.66915826 0.57918655]]


#### Advanced indexing with integer arrays

In [3]:
a = np.array([10, 20, 30, 40, 50])
index_array = np.array([0, 2, 4])
indexed_array = a[index_array]
print("Indexed array:", indexed_array)

Indexed array: [10 30 50]


#### Advanced indexing with boolean arrays

In [7]:
b = np.array([[1, 2], [3, 4], [5, 6]])
bool_idx = (b > 2)
print("Boolean indexing (b > 2):\n", bool_idx)
filtered_b = b[bool_idx]
print("Filtered array:", filtered_b)

Boolean indexing (b > 2):
 [[False False]
 [ True  True]
 [ True  True]]
Filtered array: [3 4 5 6]


#### Broadcasting

In [8]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([1, 0, 1])
broadcasted_sum = x + y
print("Broadcasted sum:\n", broadcasted_sum)

Broadcasted sum:
 [[2 2 4]
 [5 5 7]]


#### Stacking arrays depth-wise

In [9]:
depth_stack = np.dstack((x, x))
print("Depth-wise stacked array:\n", depth_stack)

Depth-wise stacked array:
 [[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]


#### Splitting arrays

In [10]:
# split into 2 sub-arrays
split_array = np.split(x, 2)  
print("Split array:", split_array)

Split array: [array([[1, 2, 3]]), array([[4, 5, 6]])]


#### Finding unique elements

In [11]:
c = np.array([1, 2, 2, 3, 3, 3])
unique_elements = np.unique(c)
print("Unique elements:", unique_elements)

Unique elements: [1 2 3]


#### Finding unique elements and their counts

In [12]:
unique_elements, counts = np.unique(c, return_counts=True)
print("Unique elements with counts:", unique_elements, counts)

Unique elements with counts: [1 2 3] [1 2 3]


### Linear algebra operations

In [13]:
matrix = np.array([[1, 2], [3, 4]])

#### Inverse of a matrix

In [15]:
inverse_matrix = np.linalg.inv(matrix)
print("Inverse of matrix:\n", inverse_matrix)

Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


#### Determinant of a matrix

In [16]:
det_matrix = np.linalg.det(matrix)
print("Determinant of matrix:", det_matrix)

Determinant of matrix: -2.0000000000000004


#### Eigen values and Eigen vectors

In [19]:
eigen = np.linalg.eig(matrix)
# this returns two values
print(eigen)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [17]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


### Solving linear equations

#### Solve Ax=b

In [20]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
solution = np.linalg.solve(A, b)
print("Solution of linear equations:", solution)

Solution of linear equations: [2. 3.]


#### Matrix multiplication

In [21]:
matrix_mul = np.matmul(A, matrix)
print("Matrix multiplication:\n", matrix_mul)

Matrix multiplication:
 [[ 6 10]
 [ 7 10]]


#### Element-wise power

In [23]:
powered_array = np.power(A, 2)
print("Element-wise power:", powered_array)

Element-wise power: [[9 1]
 [1 4]]


#### Applying a function element-wise

In [25]:
def custom_func(x):
    return x ** 2 + 1

applied_func = np.vectorize(custom_func)(A)
print("Applied custom function:", applied_func)

Applied custom function: [[10  2]
 [ 2  5]]


### Logical operators

In [29]:
logical_and = np.logical_and(a > 10, a < 50)
print("Logical AND:", logical_and)

Logical AND: [False  True  True  True False]


In [30]:
logical_or = np.logical_or(a < 10, a > 30)
print("Logical OR:", logical_or)

Logical OR: [False False False  True  True]


### Saving and loading arrays

In [4]:
np.save('saved_array.npy', a)
loaded_array = np.load('saved_array.npy')
print("Loaded array from file:", loaded_array)

Loaded array from file: [10 20 30 40 50]


#### Saving and loading text files

In [5]:
np.savetxt('saved_array.txt', a, delimiter=',')
loaded_text_array = np.loadtxt('saved_array.txt', delimiter=',')
print("Loaded array from text file:", loaded_text_array)

Loaded array from text file: [10. 20. 30. 40. 50.]


#### Generating meshgrid for 3D plots or functions

In [6]:
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)

In [7]:
X, Y = np.meshgrid(x, y)
Z = np.sin(X) + np.cos(Y)

In [8]:
print("Meshgrid X:\n", X)
print("Meshgrid Y:\n", Y)
print("Computed Z:\n", Z)

Meshgrid X:
 [[-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
   1.66666667  2.77777778  3.88888889  5.        ]
 [-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
   1.66666667  2.77777778  3.88888889  5.        ]
 [-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
   1.66666667  2.77777778  3.88888889  5.        ]
 [-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
   1.66666667  2.77777778  3.88888889  5.        ]
 [-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
   1.66666667  2.77777778  3.88888889  5.        ]
 [-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
   1.66666667  2.77777778  3.88888889  5.        ]
 [-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
   1.66666667  2.77777778  3.88888889  5.        ]
 [-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
   1.66666667  2.77777778  3.88888889 

### Applying condition to elements

In [9]:
cond_array = np.where(a > 20, a, -1)
print("Conditionally modified array:", cond_array)

Conditionally modified array: [-1 -1 30 40 50]


### Working with structured arrays

In [10]:
structured_array = np.array([(1, 'A'), (2, 'B'), (3, 'C')],
                            dtype=[('number', 'i4'), ('letter', 'U1')])
print("Structured array:", structured_array)
print("Structured array field 'number':", structured_array['number'])
print("Structured array field 'letter':", structured_array['letter'])

Structured array: [(1, 'A') (2, 'B') (3, 'C')]
Structured array field 'number': [1 2 3]
Structured array field 'letter': ['A' 'B' 'C']
